### ISSUE TITLE
Error when starting Defender.py

### ISSUE THREAD

**Issue by ToontjeM** [datagod/LEDarcade#2]
```
GroundRGB: (0, 24, 0)                                                                                                         │
Traceback (most recent call last):                                                                                            │
  File "arcade.py", line 101, in <module>                                                                                     │
    LaunchArcade(5)                                                                                                           │
  File "arcade.py", line 73, in LaunchArcade                                                                                  │
    DE.LaunchDefender(GameMaxMinutes)                                                                                         │
  File "/home/pi/LEDarcade/Defender.py", line 2215, in LaunchDefender                                                         │
    PlayDefender(GameMaxMinutes)                                                                                              │
  File "/home/pi/LEDarcade/Defender.py", line 1337, in PlayDefender                                                           │
    Ground.CreateMountains(GroundRGB,SurfaceRGB,maxheight=MaxMountainHeight)                                                  │
  File "/home/pi/LEDarcade/LEDarcade.py", line 3171, in CreateMountains                                                       │
    self.map[mv][x] = (SurfaceR, SurfaceG, SurfaceB)                                                                          │
IndexError: list index out of range  
```

**Comment by datagod** [comment]
Testing now.  Thanks for the error message.
