### ISSUE TITLE
Syntax error in LEDarcade.l

### ISSUE THREAD

**Issue by ToontjeM** [datagod/LEDarcade#8]
```
sudo python SpaceDot.py --led-gpio-mapping=adafruit-hat
Traceback (most recent call last):
  File "SpaceDot.py", line 43, in <module>
    import LEDarcade as LED
  File "/home/pi/LEDarcade/LEDarcade.py", line 12106
    print ('--',end='')
                   ^
SyntaxError: invalid syntax
```

**Comment by ToontjeM** [comment]
Need to use Python3, not python2. My fault.

**Comment by datagod** [comment]
Ok, great!  Glad you were able to resolve that.
